export const searchBar = "#q"
export const searchedItem = "computador"
export const btnSearch = ".submitBtn"
export const itens = ".sc-1fcmfeb-2"
export const navigatePageTwo = `:nth-child(2) > .sc-1m4ygug-3`
export const firstItem = ":nth-child(1) > .fnmrjs-0"
export const times = ".fnmrjs-9 > .fnmrjs-18"
export const image = ".fnmrjs-2"
export const description = ".jm5s8b-0"
export const advertiser = ".fnmrjs-8 > div"
export const location = ".fnmrjs-20"
export const adsGoogle = ".yap-gemini-pub-item"
export const adsPublicity = "[id^=listing-native-list-item]"
export const gallery = "#listing-gallery-ads"
export const adsGoogleBotton = "#module-olx-shopping"
export const adsLinks = "#adsense-slot"
