export const url = "https://www.olx.com.br/" 
export const searchBar = "#q"
export const searchedItem = "computador"
export const btnSearch = ".submitBtn"
export const itens = ".sc-1fcmfeb-2"
export const navigatePageTwo = ":nth-child(2) > .sc-1m4ygug-3"
export const firstItem = ":nth-child(1) > .fnmrjs-0"
